# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
 twitter_apikey: aV7MkrSLV0Fkg1bG2Dab4ixf3
 twitter_apisecret: JJCwJRWZXbMFrw1oMNQkSL9SZouziPzZuZe4v96L08508t524G
 twitter_oauth: 308867554-aaaTdObICLXbcyRDrESMK8SEizKkrUmIdFZHj1dw8iups9krgd
 twitter_oauthsecret: TbG9rwpR6aHdjaBQQPUnKMrvcvOf718bQr17go5QCI3bF

 admin_name: First User
 admin_email: user@example.com
 admin_password: changeme
 mail_provider_username: <%= ENV["GMAIL_USERNAME"] %>
 email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
 domain_name: example.com
 secret_key_base: 3dfd466cb59edcd3bace5a34a40f0ae94acae1938f5d7ca9f16c5b773b019c7e7bafcf0b2964b44cfb81d96cda12df79af31e3a549044735205dc2e45089e493

test:
 twitter_apikey: aV7MkrSLV0Fkg1bG2Dab4ixf3
 twitter_apisecret: JJCwJRWZXbMFrw1oMNQkSL9SZouziPzZuZe4v96L08508t524G
 twitter_oauth: 308867554-aaaTdObICLXbcyRDrESMK8SEizKkrUmIdFZHj1dw8iups9krgd
 twitter_oauthsecret: TbG9rwpR6aHdjaBQQPUnKMrvcvOf718bQr17go5QCI3bF
 domain_name: example.com
 secret_key_base: f7413076b7f00deea91a15aa6a1baab53be424bf57258310b807df57bd84ff5a572eadf810e4f9df7b70517060610cf8174001f61faae205d8227acdb79b1b95


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: example.com
  secret_key_base: 3dfd466cb59edcd3bace5a34a40f0ae94acae1938f5d7ca9f16c5b773b019c7e7bafcf0b2964b44cfb81d96cda12df79af31e3a549044735205dc2e45089e493
